version: "3.9"

services:
  go_api:
    build: .
    container_name: go_api
    restart: unless-stopped
    ports:
      - "8080:8080"
    depends_on:
      - go_db
      - redis
      - blockchain
    env_file:
      - .env
    volumes:
      - ./backend:/app
    networks:
      - go_network

  go_worker:
    build: ./backend
    container_name: go_worker
    command: go run worker.go
    depends_on:
      - go_db
      - redis
      - blockchain
    env_file:
      - .env
    volumes:
      - ./backend:/app
    networks:
      - go_network

  go_db:
    image: postgres:15
    container_name: go_db
    restart: unless-stopped
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    volumes:
      - pg_data:/var/lib/postgresql/data
    networks:
      - go_network

  redis:
    image: redis:7
    container_name: redis
    restart: unless-stopped
    ports:
      - "6379:6379"
    networks:
      - go_network

  blockchain:
    image: hyperledger/fabric-peer:2.4
    container_name: blockchain
    environment:
      - CORE_PEER_ID=${BLOCKCHAIN_PEER_ID}
      - CORE_PEER_ADDRESS=${BLOCKCHAIN_HOST}:${BLOCKCHAIN_PORT}
    ports:
      - "7051:7051"
    networks:
      - go_network

volumes:
  pg_data:

networks:
  go_network:
    driver: bridge
